openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: API для группового чата
servers:
  - url: http://localhost:8081
    description: Example server
paths:
  /load:
    get:
      summary: Загрузка сообщений чата
      parameters:
      - name: id_chat
        description: Уникальный идентификатор пользователя
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Сообщения
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not find
          content:
            application/json:
              schema:
                type: string
  /send: #Message
    post:
      summary: Создание нового сообщения
      parameters:
      - name: id_sender
        description: id пользователя
        in: query 
        required: true
        schema:
          type: integer
      - name: id_chat
        description: Оп
        in: query
        required: true
        schema:
          type: integer
      - name: text_message
        description: Текст сообщения 
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Message ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not create
          content:
            application/json:
              schema:
                type: string
  /create_gc: #Group_Chat
    post:
      summary: Создание нового чата
      parameters:
      - name: name
        description: Имя
        in: query
        required: true
        schema:
          type: string
      - name: title
        description: Описание
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Group Chat ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not create
          content:
            application/json:
              schema:
                type: string
  /add_lu: #List_Users
    post:
      summary: Добавление нового пользователя в чат
      parameters:
      - name: id_chat
        description: id чата
        in: query
        required: true
        schema:
          type: integer
      - name: id_user
        description: id пользователя
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: add to LU
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not create
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    user_id:
      description: Уникальный идентификатор пользователя
      type: integer
    users:
      type: array
      items:
        $ref: '#/components/schemas/user'
    user:
      type: object
      required:
        - id
        - first_name
        - last_name
        - email
        - title
        - login
        - password
      properties:
        id:
          $ref: '#/components/schemas/user_id'
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        title:
          type: string
        login:
          type: string
        password:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []